# -*- coding: utf-8 -*-
"""nlp_unit_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5fhzaTUQdyLOInsjsBwQV57kJQIXBcx
"""

# CHATBOT
def chatbot():
    print("Chatbot: Hello! Type 'bye' to exit.")

    while True:
        user_input = input("You: ").lower()

        if user_input == "hi":
            print("Chatbot: Hello!")
        elif user_input == "how are you":
            print("Chatbot: I am fine. How can I help you?")
        elif user_input == "your name":
            print("Chatbot: I am a simple chatbot.")
        elif user_input == "bye":
            print("Chatbot: Goodbye!")
            break
        else:
            print("Chatbot: I don't understand.")

chatbot()

# QA SYSTEM
from transformers import pipeline

class PracticeProgramQA:
    def __init__(self, model_name="deepset/roberta-base-squad2"):
        # Initialize the question-answering pipeline
        print(f"Loading model: {model_name}...")
        self.qa_pipeline = pipeline("question-answering", model=model_name, tokenizer=model_name)
        print("Model loaded successfully.")

    def answer_question(self, question: str, context: str) -> dict:
        """
        Extracts the answer to a question from the provided context.
        """
        try:
            result = self.qa_pipeline(question=question, context=context)
            return {
                "question": question,
                "answer": result['answer'],
                "confidence_score": round(result['score'], 4),
                "start_idx": result['start'],
                "end_idx": result['end']
            }
        except Exception as e:
            return {"error": str(e)}

# --- Example Usage ---
if __name__ == "__main__":
    qa_system = PracticeProgramQA()

    # The text your system will search through
    practice_context = """
    Welcome to the Artificial Intelligence practice program.
    This curriculum covers fundamental concepts including Tokenization, Attention Mechanisms, and Transformer Architectures.
    The final assessment is scheduled for the last week of the semester.
    To pass the certification, students must achieve a minimum score of 80% on all practical assignments.
    """

    user_question = "What score is required to pass the certification?"

    # Get the answer
    response = qa_system.answer_question(question=user_question, context=practice_context)

    print("\n--- QA Results ---")
    print(f"Question: {response['question']}")
    print(f"Answer:   {response['answer']}")
    print(f"Confidence: {response['confidence_score']}")

# TEXT SUMMARIZER

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

class TextSummarizer:
    def __init__(self, model_name="facebook/bart-large-cnn"):
        """
        Initializes the summarizer explicitly without relying on the legacy pipeline.
        """
        print(f"Loading model: {model_name}...")
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
        print("Model loaded successfully.")

    def summarize_text(self, text: str, max_length: int = 130, min_length: int = 30) -> str:
        """
        Summarizes the provided text using explicit tokenization and generation.
        """
        try:
            # 1. Tokenize the input text
            # (BART handles raw text directly, truncation ensures we don't exceed the 1024 token limit)
            inputs = self.tokenizer(text, return_tensors="pt", max_length=1024, truncation=True)

            # 2. Generate summary tokens
            summary_ids = self.model.generate(
                inputs["input_ids"],
                max_length=max_length,
                min_length=min_length,
                do_sample=False # Set to True for more varied summaries
            )

            # 3. Decode the generated tokens back to a readable string
            summary = self.tokenizer.decode(summary_ids[0], skip_special_tokens=True)
            return summary
        except Exception as e:
            return f"Error during summarization: {str(e)}"

# --- Example Usage ---
if __name__ == "__main__":
    summarization_system = TextSummarizer()

    source_text = """
    Artificial intelligence (AI) is intelligence demonstrated by machines, as opposed to the natural intelligence
    displayed by animals including humans. AI research has been defined as the field of study of intelligent agents,
    which refers to any system that perceives its environment and takes actions that maximize its chance of achieving its goals.
    The term "artificial intelligence" had previously been used to describe machines that mimic and display "human" cognitive
    skills that are associated with the human mind, such as "learning" and "problem-solving". This definition has since been
    rejected by major AI researchers who now describe AI in terms of rationality and acting rationally, which does not limit
    how intelligence can be articulated.
    """

    print("\nSummarizing text...")
    summary = summarization_system.summarize_text(text=source_text, max_length=50, min_length=15)

    print("\n--- Results ---")
    print(f"Summary:\n{summary}")

# MACHINE TRANSLATOR

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

class MachineTranslator:
    def __init__(self, model_name="Helsinki-NLP/opus-mt-en-es"):
        """
        Initializes the translation system.
        We are using an English-to-Spanish model by default.
        You can swap 'en-es' with 'en-fr' (French), 'en-de' (German), etc.
        """
        print(f"Loading translation model: {model_name}...")

        # Explicitly load the tokenizer and model
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

        print("Model loaded successfully.")

    def translate_text(self, text: str) -> str:
        """
        Translates the input text using the loaded model.
        """
        try:
            # 1. Tokenize the input text
            # padding and truncation ensure it handles varying text lengths safely
            inputs = self.tokenizer(text, return_tensors="pt", padding=True, truncation=True)

            # 2. Generate the translated tokens
            translated_tokens = self.model.generate(**inputs)

            # 3. Decode the tokens back into human-readable text
            translation = self.tokenizer.decode(translated_tokens[0], skip_special_tokens=True)
            return translation

        except Exception as e:
            return f"Error during translation: {str(e)}"

# --- Example Usage ---
if __name__ == "__main__":
    # Initialize the English to Spanish translator
    translator = MachineTranslator()

    # The text to translate
    english_text = """
    Artificial intelligence is rapidly transforming the way we build software.
    By integrating language models, we can automate complex tasks and improve user experiences.
    """

    print("\nTranslating to Spanish...")
    spanish_translation = translator.translate_text(text=english_text)

    print("\n--- Results ---")
    print(f"Original (EN): {english_text.strip()}")
    print(f"Translated (ES): {spanish_translation}")